In [10]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [13]:
dataset = pd.read_csv(r'C:\Users\amits\Desktop\AI Final\Bigmart\Train.csv')

In [14]:
dataset.head()

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0           FDA15         9.30          Low Fat         0.016047   
1           DRC01         5.92          Regular         0.019278   
2           FDN15        17.50          Low Fat         0.016760   
3           FDX07        19.20          Regular         0.000000   
4           NCD19         8.93          Low Fat         0.000000   

               Item_Type  Item_MRP Outlet_Identifier  \
0                  Dairy  249.8092            OUT049   
1            Soft Drinks   48.2692            OUT018   
2                   Meat  141.6180            OUT049   
3  Fruits and Vegetables  182.0950            OUT010   
4              Household   53.8614            OUT013   

   Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                       1999      Medium               Tier 1   
1                       2009      Medium               Tier 3   
2                       1999      Medium               Tier 1   
3                       1998         NaN               Tier 3   
4                       1987        High               Tier 3   

         Outlet_Type  Item_Outlet_Sales  
0  Supermarket Type1          3735.1380  
1  Supermarket Type2           443.4228  
2  Supermarket Type1          2097.2700  
3      Grocery Store           732.3800  
4  Supermarket Type1           994.7052

In [18]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:,-1].values
print(y)

[3735.138   443.4228 2097.27   ... 1193.1136 1845.5976  765.67  ]


In [9]:
from sklearn_pandas import CategoricalImputer

In [10]:
cimputer = CategoricalImputer()

In [20]:
dataset.iloc[:,2].values

array(['Low Fat', 'Regular', 'Low Fat', ..., 'Low Fat', 'Regular',
       'Low Fat'], dtype=object)

In [12]:
data = np.array(X[:,2], dtype='object')

In [13]:
X[:,2] = cimputer.fit_transform(data)
dataset['Item_Fat_Content'] = X[:,2]

In [14]:
dataset.iloc[:,2].isnull().any()

False

In [15]:
data1 = np.array(X[:, 8], dtype='object')
X[:,8] = cimputer.fit_transform(data1)

In [16]:
dataset['Outlet_Size'] = X[:,8]

In [17]:
dataset.iloc[:,8].isnull().any()

False

In [18]:
dataset.iloc[:].isnull().any()

Item_Identifier              False
Item_Weight                   True
Item_Fat_Content             False
Item_Visibility              False
Item_Type                    False
Item_MRP                     False
Outlet_Identifier            False
Outlet_Establishment_Year    False
Outlet_Size                  False
Outlet_Location_Type         False
Outlet_Type                  False
Item_Outlet_Sales            False
dtype: bool

In [34]:
from sklearn.preprocessing import Imputer

In [35]:
imputer = Imputer(missing_values='NaN', strategy='mean')

c:\users\amits\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [36]:
X[:,1:2] = imputer.fit_transform(X[:,1:2])

In [37]:
dataset['Item_Weight'] = X[:,1:2]

In [38]:
dataset.isnull().any()

Item_Identifier              False
Item_Weight                  False
Item_Fat_Content             False
Item_Visibility              False
Item_Type                    False
Item_MRP                     False
Outlet_Identifier            False
Outlet_Establishment_Year    False
Outlet_Size                  False
Outlet_Location_Type         False
Outlet_Type                  False
Item_Outlet_Sales            False
dtype: bool

In [39]:
dataset['Item_Fat_Content'] = dataset['Item_Fat_Content'].replace({'low fat':'Low Fat', 'LF':'Low Fat', 'reg':'Regular'})

In [40]:
dataset.head()

Item_Identifier Item_Weight Item_Fat_Content  Item_Visibility  \
0           FDA15         9.3          Low Fat         0.016047   
1           DRC01        5.92          Regular         0.019278   
2           FDN15        17.5          Low Fat         0.016760   
3           FDX07        19.2          Regular         0.000000   
4           NCD19        8.93          Low Fat         0.000000   

               Item_Type  Item_MRP Outlet_Identifier  \
0                  Dairy  249.8092            OUT049   
1            Soft Drinks   48.2692            OUT018   
2                   Meat  141.6180            OUT049   
3  Fruits and Vegetables  182.0950            OUT010   
4              Household   53.8614            OUT013   

   Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                       1999      Medium               Tier 1   
1                       2009      Medium               Tier 3   
2                       1999      Medium               Tier 1   
3                       1998      Medium               Tier 3   
4                       1987        High               Tier 3   

         Outlet_Type  Item_Outlet_Sales  
0  Supermarket Type1          3735.1380  
1  Supermarket Type2           443.4228  
2  Supermarket Type1          2097.2700  
3      Grocery Store           732.3800  
4  Supermarket Type1           994.7052

In [41]:
from sklearn.preprocessing import LabelEncoder

In [42]:
labelEncoder = LabelEncoder()

In [43]:
mod = ['Item_Fat_Content', 'Item_Type', 'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Type']
dataset['Item_Identifier'] = labelEncoder.fit_transform(dataset['Item_Identifier'])
dataset['Outlet_Identifier'] = labelEncoder.fit_transform(dataset['Outlet_Identifier'])

for i in mod:
    dataset[i] = labelEncoder.fit_transform(dataset[i])

In [44]:
X = dataset.iloc[:].values

In [45]:
X

array([[156, 9.3, 0, ..., 0, 1, 3735.138],
       [8, 5.92, 1, ..., 2, 2, 443.4228],
       [662, 17.5, 0, ..., 0, 1, 2097.27],
       ...,
       [1357, 10.6, 0, ..., 1, 1, 1193.1136],
       [681, 7.21, 1, ..., 2, 2, 1845.5976],
       [50, 14.8, 0, ..., 0, 1, 765.67]], dtype=object)

In [46]:
y

array([3735.138 ,  443.4228, 2097.27  , ..., 1193.1136, 1845.5976,
        765.67  ])

In [47]:
from sklearn.model_selection import train_test_split

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=0)

In [49]:
from sklearn.linear_model import LinearRegression

In [50]:
model = LinearRegression()

In [51]:
rgsr = model.fit(X_train, y_train)

In [52]:
model.score(X_test, y_test)

1.0

In [53]:
model.score(X_train, y_train)

1.0

In [54]:
y_pred = model.predict(X_test)

In [55]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [56]:
print(y_pred)

[1426.1436 1201.769  1836.2764 ... 3325.671  8479.6288 1342.2528]


In [57]:
from math import sqrt
from sklearn.metrics import mean_squared_error

In [58]:
rms = sqrt(mean_squared_error(y_test, y_pred))
print(rms)

1.7151899309200906e-11


In [59]:
X_df = pd.DataFrame(X_test)
y_df = pd.DataFrame(y_pred)

In [60]:
Headers = pd.DataFrame(dataset.iloc[:])

In [61]:
result = pd.concat([Headers, X_df, y_df], axis=1, ignore_index=True)

In [63]:
result.to_csv(r"C:\Users\amits\Desktop\Bigmart\results.csv", index=False)