In [2]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn


In [3]:
dataset = pd.read_csv(r"C:\Users\DELL\Desktop\LP1\LP I (AI x 7)\16 bigmart\Train.csv")

In [4]:
dataset.head()

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0           FDA15         9.30          Low Fat         0.016047   
1           DRC01         5.92          Regular         0.019278   
2           FDN15        17.50          Low Fat         0.016760   
3           FDX07        19.20          Regular         0.000000   
4           NCD19         8.93          Low Fat         0.000000   

               Item_Type  Item_MRP Outlet_Identifier  \
0                  Dairy  249.8092            OUT049   
1            Soft Drinks   48.2692            OUT018   
2                   Meat  141.6180            OUT049   
3  Fruits and Vegetables  182.0950            OUT010   
4              Household   53.8614            OUT013   

   Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                       1999      Medium               Tier 1   
1                       2009      Medium               Tier 3   
2                       1999      Medium               Tier 1   
3                       1998         NaN               Tier 3   
4                       1987        High               Tier 3   

         Outlet_Type  Item_Outlet_Sales  
0  Supermarket Type1          3735.1380  
1  Supermarket Type2           443.4228  
2  Supermarket Type1          2097.2700  
3      Grocery Store           732.3800  
4  Supermarket Type1           994.7052

In [6]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:,-1].values
print(X)
print(y)


[['FDA15' 9.3 'Low Fat' ... 'Medium' 'Tier 1' 'Supermarket Type1']
 ['DRC01' 5.92 'Regular' ... 'Medium' 'Tier 3' 'Supermarket Type2']
 ['FDN15' 17.5 'Low Fat' ... 'Medium' 'Tier 1' 'Supermarket Type1']
 ...
 ['NCJ29' 10.6 'Low Fat' ... 'Small' 'Tier 2' 'Supermarket Type1']
 ['FDN46' 7.21 'Regular' ... 'Medium' 'Tier 3' 'Supermarket Type2']
 ['DRG01' 14.8 'Low Fat' ... 'Small' 'Tier 1' 'Supermarket Type1']]


AttributeError: 'NoneType' object has no attribute 'all'

In [25]:
from sklearn import CategoricalImputer

ImportError: cannot import name 'CategoricalImputer' from 'sklearn' (C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\__init__.py)

In [12]:
cimputer = CategoricalImputer()

NameError: name 'CategoricalImputer' is not defined

In [7]:
dataset.iloc[:,2].values

array(['Low Fat', 'Regular', 'Low Fat', ..., 'Low Fat', 'Regular',
       'Low Fat'], dtype=object)

In [8]:
data = np.array(X[:,2], dtype='object')

In [9]:
X[:,2] = cimputer.fit_transform(data)
dataset['Item_Fat_Content'] = X[:,2]

In [10]:
dataset.iloc[:,2].isnull().any()

False

In [11]:
data1 = np.array(X[:, 8], dtype='object')
X[:,8] = cimputer.fit_transform(data1)

In [12]:
dataset['Outlet_Size'] = X[:,8]

In [13]:
dataset.iloc[:,8].isnull().any()

False

In [14]:
dataset.iloc[:].isnull().any()

Item_Identifier              False
Item_Weight                   True
Item_Fat_Content             False
Item_Visibility              False
Item_Type                    False
Item_MRP                     False
Outlet_Identifier            False
Outlet_Establishment_Year    False
Outlet_Size                  False
Outlet_Location_Type         False
Outlet_Type                  False
Item_Outlet_Sales            False
dtype: bool

In [15]:
from sklearn.preprocessing import Imputer

In [16]:
imputer = Imputer(missing_values='NaN', strategy='mean')

C:\Users\asbaj\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [17]:
X[:,1:2] = imputer.fit_transform(X[:,1:2])

In [18]:
dataset['Item_Weight'] = X[:,1:2]

In [19]:
dataset.isnull().any()

Item_Identifier              False
Item_Weight                  False
Item_Fat_Content             False
Item_Visibility              False
Item_Type                    False
Item_MRP                     False
Outlet_Identifier            False
Outlet_Establishment_Year    False
Outlet_Size                  False
Outlet_Location_Type         False
Outlet_Type                  False
Item_Outlet_Sales            False
dtype: bool

In [20]:
dataset['Item_Fat_Content'] = dataset['Item_Fat_Content'].replace({'low fat':'Low Fat', 'LF':'Low Fat', 'reg':'Regular'})

In [21]:
dataset.head()

Item_Identifier Item_Weight Item_Fat_Content  Item_Visibility  \
0           FDA15         9.3          Low Fat         0.016047   
1           DRC01        5.92          Regular         0.019278   
2           FDN15        17.5          Low Fat         0.016760   
3           FDX07        19.2          Regular         0.000000   
4           NCD19        8.93          Low Fat         0.000000   

               Item_Type  Item_MRP Outlet_Identifier  \
0                  Dairy  249.8092            OUT049   
1            Soft Drinks   48.2692            OUT018   
2                   Meat  141.6180            OUT049   
3  Fruits and Vegetables  182.0950            OUT010   
4              Household   53.8614            OUT013   

   Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                       1999      Medium               Tier 1   
1                       2009      Medium               Tier 3   
2                       1999      Medium               Tier 1   
3                       1998      Medium               Tier 3   
4                       1987        High               Tier 3   

         Outlet_Type  Item_Outlet_Sales  
0  Supermarket Type1          3735.1380  
1  Supermarket Type2           443.4228  
2  Supermarket Type1          2097.2700  
3      Grocery Store           732.3800  
4  Supermarket Type1           994.7052

In [22]:
from sklearn.preprocessing import LabelEncoder

In [23]:
labelEncoder = LabelEncoder()

In [24]:
mod = ['Item_Fat_Content', 'Item_Type', 'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Type']
dataset['Item_Identifier'] = labelEncoder.fit_transform(dataset['Item_Identifier'])
dataset['Outlet_Identifier'] = labelEncoder.fit_transform(dataset['Outlet_Identifier'])

for i in mod:
    dataset[i] = labelEncoder.fit_transform(dataset[i])

In [25]:
X = dataset.iloc[:].values

In [26]:
X

array([[156, 9.3, 0, ..., 0, 1, 3735.138],
       [8, 5.92, 1, ..., 2, 2, 443.4228],
       [662, 17.5, 0, ..., 0, 1, 2097.27],
       ...,
       [1357, 10.6, 0, ..., 1, 1, 1193.1136],
       [681, 7.21, 1, ..., 2, 2, 1845.5976],
       [50, 14.8, 0, ..., 0, 1, 765.67]], dtype=object)

In [27]:
y

array([3735.138 ,  443.4228, 2097.27  , ..., 1193.1136, 1845.5976,
        765.67  ])

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=0)

In [30]:
from sklearn.linear_model import LinearRegression

In [31]:
model = LinearRegression()

In [32]:
rgsr = model.fit(X_train, y_train)

In [33]:
model.score(X_test, y_test)

1.0

In [34]:
model.score(X_train, y_train)

1.0

In [35]:
y_pred = model.predict(X_test)

In [36]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [37]:
print(y_pred)

[1426.1436 1201.769  1836.2764 ... 3325.671  8479.6288 1342.2528]


In [38]:
from math import sqrt
from sklearn.metrics import mean_squared_error

In [39]:
rms = sqrt(mean_squared_error(y_test, y_pred))
print(rms)

1.6827013667986343e-11


In [40]:
X_df = pd.DataFrame(X_test)
y_df = pd.DataFrame(y_pred)

In [41]:
Headers = pd.DataFrame(dataset.iloc[:])

In [42]:
result = pd.concat([Headers, X_df, y_df], axis=1, ignore_index=True)

In [43]:
result.to_csv("C://Users/Admin/Downloads/results.csv", index=False)

FileNotFoundError: [Errno 2] No such file or directory: 'C://Users/Admin/Downloads/results.csv'